SHOW DATABASES;
-- CREATING NEW DATABASES 
CREATE DATABASE PYTHON_DATA_SCIENCE;

-- SHOWING AGAIN DATABASES
SHOW DATABASES;

-- USING ON PYTHON_DATA_SCIENCE 
USE PYTHON_DATA_SCIENCE

-- WORKING ON ABOVE DATABASE/ WHICH DATABASE YOU ARE WORKING
SELECT DATABASE();

-- DELETING ABOVE PYTHON_DATA_SCIENCE DATABASE 
DROP DATABASE PYTHON_DATA_SCIENCE; 

-- SHOWING AGAIN DATABASES
SHOW DATABASES;

-- CREATING SCHOOL DATABASE
CREATE DATABASE SCHOOL;

-- USING SCHOOL DATABASE
USE SCHOOL;

-- SEE SELECTED DATABASE
SELECT DATABASE();

-- CREATING students table in SCHOOL DATABASE 
CREATE TABLE students (Roll_no int, Name varchar(50));

-- DESCRIBING TABLE students 
DESCRIBE students;

-- DROPING/DELETING TABLE students 
DROP TABLE students;

-- SHOWING TABLE 
SHOW TABLES;

-- ALTER TABLE OR MODIFY TABLE students 
-- ADDING NEW COLUMN Class int
ALTER TABLE students ADD Class int;
DESCRIBE students;

-- ADDING NEW COLUMN Age int
ALTER TABLE students ADD Age varchar(10);
DESCRIBE students;

-- DROPING COLUMN Age 
ALTER TABLE students DROP COLUMN Age;
DESCRIBE students;

ALTER TABLE students ADD Age varchar(10);
DESCRIBE students;
-- MODIFYING COLUMN Age converting varchar into int 
ALTER TABLE students MODIFY COLUMN Age int;
DESCRIBE students;

